### ISSUE TITLE
Adding to 🐸TTS 

### ISSUE THREAD

**Issue by erogol** [robinhad/ukrainian-tts#1]
Thx for the model. I'm going to add it to our models in [🐸TTS](https://github.com/coqui-ai/TTS). 

BTW do you plan to train a Vocoder?

**Comment by robinhad** [comment]
hi @erogol,
why default vocoder wouldn't work?

**Comment by erogol** [comment]
Hi.. Audio parameters don't match

**Comment by robinhad** [comment]
Could you tell me how to use a vocoder during training?
I can't find anything in docs or code

**Comment by robinhad** [comment]
@erogol, vocoder is available in Release, you can test model on HuggingFace Spaces as well

**Comment by NeonBohdan** [comment]
@erogol This model has been improved much, please update it in [TTS](https://github.com/coqui-ai/TTS) with version [1.0.0](https://github.com/robinhad/ukrainian-tts/releases/tag/v1.0.0)

**Comment by erogol** [comment]
Added to the TODO list. https://github.com/coqui-ai/TTS/issues/378
