### ISSUE TITLE
Error with file: speakers.pth

### ISSUE THREAD

**Issue by akirsoft** [robinhad/ukrainian-tts#13]
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/Soft/Python/mamba1/TTS/vits_mykyta_latest-September-12-2022_12+38AM-829e2c24/speakers.pth'

**Comment by robinhad** [comment]
can you provide code snippet to reproduce?

**Comment by akirsoft** [comment]
from ukrainian_tts.tts import TTS, Voices

tts = TTS()
with open("test.wav", mode="wb") as file:
    _, text = tts.tts("Привіт, Пол+іна! Сподіваюся, голова вже не болить?" , Voices.Mykyta.value, "dictionary", file)
    print("Accented text:", text)

**Comment by akirsoft** [comment]
I rewrited file json and added my path '/home/user/Soft/Python/mamba1/TTS, but vits_mykyta_latest-September-12-2022_12+38AM-829e2c24/speakers.pth in config.json

**Comment by robinhad** [comment]
Should be solved now, please reopen if not
